coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: 70%
        informational: true

ignore:
  - "tests" # Don't include the tests themselves in the code coverage report
