# West manifest for Memfault Example Application

manifest:

  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: v3.6.0
      import:
        # Limit the Zephyr modules to the required set
        name-allowlist:
            - cmsis
            - hal_stm32
            - picolibc
            - tinycrypt

    - name: memfault-firmware-sdk
      path: modules/lib/memfault-firmware-sdk
      url: https://github.com/memfault/memfault-firmware-sdk
      # Memfault recommends pinning to a specific release tag for production
      revision: master
